![PPGI_UFRJ](imagens/ppgi-ufrj.png)
# Fundamentos de Ciência de Dados

---
# PPGI/UFRJ 2020.3
## Prof Sergio Serra e Jorge Zavaleta

# Módulo 2 - Numpy

## Numpy

Biblioteca para Computação científica com Python. Pode ser encontrada em [Numpy](https://numpy.org/doc/stable/). Esta biblioteca permite realizar operações eficientes em estruturas de dados usadas em aprendizado de máquina (*machine learning*): **vetores**, **matrizes** e **tensores**.

- Importando o pacote NUMPY

In [1]:
# importando o pacote
import numpy as np
# version do numpy
print(np.version.version)

1.19.2


- Vetores e matrizes de **n** dimensões: **ndarray**

In [2]:
# exemplo - vetor
v = [12, 10, -1, 4] # lista
print('v:',type(v))
# convertir uma lista em vetor
v1 = np.array(v)
print('v1:',type(v1))
print('v1 =',v1)
#v = [1,2,3 4]


v: <class 'list'>
v1: <class 'numpy.ndarray'>
v1 = [12 10 -1  4]


In [3]:
# criando um vetor fila ou linha
vetor = np.array([-1, 0.5, 20, 4, -2.0, 20])
print('v:',vetor)
print(len(vetor))

v: [-1.   0.5 20.   4.  -2.  20. ]
6


In [4]:
# criar vetor coluna
vetor_c = np.array([[-1],[0.5],[20],[4],[-2.0]])
vetor_c

array([[-1. ],
       [ 0.5],
       [20. ],
       [ 4. ],
       [-2. ]])

In [5]:
# criando uma matriz
matriz_3x3 = np.array([[4,6,2],[8,-1,0],[3,4,5]])
matriz_3x3

array([[ 4,  6,  2],
       [ 8, -1,  0],
       [ 3,  4,  5]])

In [6]:
# funcoes: len e shape
# tamanho do vetor/matriz:len()
print('T:',len(matriz_3x3))
# dimesoes do vetor/matriz: shape
print('D:',matriz_3x3.shape)

T: 3
D: (3, 3)


In [7]:
# exemplo de tamanho e dimensao
A = np.array([[1,-1],[3, -2],[4,2]])
print(A)
print('Tam =',len(A)) #tamanho 
print('Dim =',A.ndim) #dimensoes
print('Dim =',A.shape) # dimensoes(fila, coluna)  

[[ 1 -1]
 [ 3 -2]
 [ 4  2]]
Tam = 3
Dim = 2
Dim = (3, 2)


### Métodos

- **narray.ndim** - Dimensões do *array*
- **narray.shape** - Número de elementos em cada dimensão no array, (n,m)
- **narray.size** - Tamanho do array (total de elementos), nxm
- **narray.reshape** - Redimensão do array nxm

In [8]:
# exemplo de size
print('T :',A.size)
B = A.reshape(2,3)
print('B :',B)
BB = A.reshape(1,6)
print(BB)
B1 = A.reshape(6,1)
print(B1)

T : 6
B : [[ 1 -1  3]
 [-2  4  2]]
[[ 1 -1  3 -2  4  2]]
[[ 1]
 [-1]
 [ 3]
 [-2]
 [ 4]
 [ 2]]


In [9]:
# exemplo: len, ndim, shape, size e reshape
A1 = np.array( [ (1,2,3), (4,5,6), (2,7,8) ])
A1.shape

(3, 3)

In [10]:
# exemplo
A2 = np.arange(60).reshape(3,4,5)
print(A2)
A11 = np.arange(60).reshape(20,3)
print(A11)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]]


- Gerando valores com a função **linspace**

In [11]:
# Geracao devalores usando a funcao: linspace
pesos_turma = np.linspace(50,80,num=40)
print(pesos_turma)

[50.         50.76923077 51.53846154 52.30769231 53.07692308 53.84615385
 54.61538462 55.38461538 56.15384615 56.92307692 57.69230769 58.46153846
 59.23076923 60.         60.76923077 61.53846154 62.30769231 63.07692308
 63.84615385 64.61538462 65.38461538 66.15384615 66.92307692 67.69230769
 68.46153846 69.23076923 70.         70.76923077 71.53846154 72.30769231
 73.07692308 73.84615385 74.61538462 75.38461538 76.15384615 76.92307692
 77.69230769 78.46153846 79.23076923 80.        ]


In [12]:
# modificando a forma do vetor: reshape
D2 = pesos_turma.reshape((4,10))
D2

array([[50.        , 50.76923077, 51.53846154, 52.30769231, 53.07692308,
        53.84615385, 54.61538462, 55.38461538, 56.15384615, 56.92307692],
       [57.69230769, 58.46153846, 59.23076923, 60.        , 60.76923077,
        61.53846154, 62.30769231, 63.07692308, 63.84615385, 64.61538462],
       [65.38461538, 66.15384615, 66.92307692, 67.69230769, 68.46153846,
        69.23076923, 70.        , 70.76923077, 71.53846154, 72.30769231],
       [73.07692308, 73.84615385, 74.61538462, 75.38461538, 76.15384615,
        76.92307692, 77.69230769, 78.46153846, 79.23076923, 80.        ]])

## Indexação
Visualizar algúm valor do array ou mudar em valor usando o índice de indexação.

In [13]:
# exemplo: Visializar o elemento 2,3 do matriz D2
d23 = D2[2,3]
print(d23)
d00 = D2[0,0]
print(d00)

67.6923076923077
50.0


In [14]:
# exemplo: mudar o valor do elemento d23 = -1.0
D2[2,3] = -1.0
d23 = D2[2,3]
print(d23)
print(D2)

-1.0
[[50.         50.76923077 51.53846154 52.30769231 53.07692308 53.84615385
  54.61538462 55.38461538 56.15384615 56.92307692]
 [57.69230769 58.46153846 59.23076923 60.         60.76923077 61.53846154
  62.30769231 63.07692308 63.84615385 64.61538462]
 [65.38461538 66.15384615 66.92307692 -1.         68.46153846 69.23076923
  70.         70.76923077 71.53846154 72.30769231]
 [73.07692308 73.84615385 74.61538462 75.38461538 76.15384615 76.92307692
  77.69230769 78.46153846 79.23076923 80.        ]]


In [15]:
# verificando condicoes
C = D2 > 10
C

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [16]:
# condicoes para achar outliers e mudar
D2[D2>4] = 2
E = D2
E

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2., -1.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]])

### Manipulando valores que não existentes: nan

In [17]:
# valores de um arquivo
X = np.array([0,-2.10, 4, 6, 20, 30, -10, np.NAN, 3, 5]) #
X

array([  0. ,  -2.1,   4. ,   6. ,  20. ,  30. , -10. ,   nan,   3. ,
         5. ])

In [18]:
# verificando se existe algum valor nao numerico
Y = np.isnan(X)
print(Y)

[False False False False False False False  True False False]


In [19]:
# exemplo: eleminar o elemento indesejado de um vetor
X = X[~np.isnan(X)]
print(X)

[  0.   -2.1   4.    6.   20.   30.  -10.    3.    5. ]


In [20]:
# exemplo: eleiminar um elemento indesejado de uma matriz
M = np.array([[1, 2, np.NAN],[np.NAN, -1, 0.5],[1, 2, 4]])
M

array([[ 1. ,  2. ,  nan],
       [ nan, -1. ,  0.5],
       [ 1. ,  2. ,  4. ]])

In [21]:
# verificando a existencia de valores indesejados
Y1 = np.isnan(M)
print(Y1)

[[False False  True]
 [ True False False]
 [False False False]]


In [22]:
# eliminar os elementos indesejandos
print(Y1.shape)
print(M[0,2])
M[0,2] = 10
print(M[1,0])
M[1,0] = 10
print(M)

(3, 3)
nan
nan
[[ 1.   2.  10. ]
 [10.  -1.   0.5]
 [ 1.   2.   4. ]]


In [23]:
M1 = np.array([[1, 2, np.NAN],[np.NAN, -1, 0.5],[1, 2, 4]])
print('M1 :',M1)
print('In:',np.isnan(M1))

M1 : [[ 1.   2.   nan]
 [ nan -1.   0.5]
 [ 1.   2.   4. ]]
In: [[False False  True]
 [ True False False]
 [False False False]]


In [24]:
# mudando o valor de um elemento
(l,c) = M1.shape # dimensoes da matriz
for L in range(l):
    for C in range(c):
        MT = np.isnan(M1)
        if MT[L,C]==True:
            M1[L,C] = 10
print('M1:',M1)

M1: [[ 1.   2.  10. ]
 [10.  -1.   0.5]
 [ 1.   2.   4. ]]


### Fatiando um vetor/matriz

In [ ]:
# usando a funcao: slice
print('M1:')
print(M1)
print()
# slice primeira linha
print('L1:',M1[0,:])

In [ ]:
# slice a segunda linha ou fila
print('L2:',M1[1,:])

In [ ]:
# slice a primeira coluna
print('C0:',M1[:,0])

In [ ]:
# slice a ultima coluna
print('C0:',M1[:,2])

In [ ]:
# slice = toda a matriz
print('M1',M1[:,:])

In [ ]:
# slice para usa submatriz
sm = M1[1:,2:]
print(sm)

In [ ]:
# slice para submatriz
sm1 = M1[1:,:2]
print(sm1)

In [ ]:
# usando a funcao:copy
C1 = np.array([[1],[2],[1]])
C2 = C1
# mudar um valor de C2
print(C1)
C2[0,0]=-10
print('C2:')
print(C2)
# Visualizar mudancas no C1
print('C1:')
print(C1)

In [ ]:
# Usando a funcao Copy
import copy
C3 = copy.deepcopy(C2)
print('C3:')
print(C3)
C3[0,0] = 1000
print(C3)
print(C2)

### Criando matrizes de pontos uniformemente espaçados com linspace()

In [ ]:
# criando matrizes
P = np.linspace(0,5,50)
Q = np.linspace(5,11,50)
print(P)
print(Q)
print(len(P))
print(len(Q))

In [ ]:
XX = P + Q
print(XX)
pp = P*Q
print(pp)

### zeros()

In [ ]:
# cria matriz de zeros
z = np.zeros((10,10))
z

In [ ]:
z1 = np.zeros((3,3),dtype=complex)
z1

In [ ]:
z2 = np.zeros((3,3),dtype=complex)
z2

### ones()

In [ ]:
o = np.ones((4,4))
o

In [ ]:
os = np.ones((4,4),dtype=complex)
os

### eye()

In [ ]:
# Matriz diagonal
e = np.eye(3,k=0)
e

In [ ]:
# Matriz diagonal
e1 = np.eye(3,k=-1)
e1

In [ ]:
# Matriz diagonal
e2 = np.eye(3,k=-1)
e2

### Matriz identidade

In [ ]:
# matriz identidade
i = np.identity(5)
i

In [ ]:
# preenche dados especificos
f = np.full((3,3),3.14,dtype=float)
f

### Numeros Aleatórios

In [ ]:
# numero aleatorios: vetor
r = np.random.rand(4)
r

In [ ]:
# numero aleatorios: matriz
r1 = np.random.rand(4,4)
r1

In [ ]:
# numero aleatorios inteiros
r2 = np.random.randint(0,5,3)
r2

### Estátistica básica

In [ ]:
# exemplo: narray
peso_kg = np.linspace(55,90,num=40)
print('Peso em Kg:')
print(peso_kg)

In [ ]:
# funcoes estatisticas
# media aritmetica
media = peso_kg.mean()
print('Média da turma :',media)
# maximo
maximo = peso_kg.max()
print('Máximo da turma :',maximo)
# minimo
minimo = peso_kg.min()
print('Mínimo da turma :',minimo)
# somatorio
soma = peso_kg.sum()
print('Somatorio dos valores da turma :',soma)
# desvio padrao
desv = peso_kg.std()
print('Desvio padrão dos valores da turma :',desv)
vart = peso_kg.var()
print('Variância dos valores da turma :',vart)

**Observação**: Para variância e desvio padrão de amostras, acrescentar ddof=1 (delta degrees of freedom)

In [ ]:
desv1 = peso_kg.std(ddof=1)
print('Desvio padrão dos valores da turma :',desv1)
vart1 = peso_kg.var(ddof=1)
print('Variância dos valores da turma :',vart1)

In [ ]:
# Histograma
# importando a biblioteca para graficos
from matplotlib import pyplot as plt  
plt.hist(peso_kg, bins = [50, 60, 70, 80, 90, 100],color='r',alpha=0.3) 
plt.title("Numpy Histograma")
plt.xlabel('Peso da turma')
plt.ylabel('Frequência')
plt.grid(True)
# show plot 
plt.show()

In [ ]:
# cria uma sequenci de valores
seq = np.random.randn(50)
seq

1. Exercicio. Usando o vetor seq, calcule todas as medidas estatísticas de tendencia central e apresente o gráfico.
2. Cria vetor com 50 valores. 
    - verifique o comprimento, ndim, shape
    - Convertir o vetor em matriz
    - criar uma submatriz de 4x4
    - Determinar as medidas estatísticas para o vetor
    - Grafique o histograma do vetor

---
#### Fudamentos para Ciência Dados &copy; Copyright 2021, Sergio Serra & Jorge Zavaleta